/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FCGPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var FCGPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Todo build the application!");
  }
  async onunload() {
    console.log("Todo build the application!");
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsic3JjL21haW4udHMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbIlxuaW1wb3J0IHsgUGx1Z2luIH0gZnJvbSBcIm9ic2lkaWFuXCJcblxuXG5leHBvcnQgZGVmYXVsdCBjbGFzcyBGQ0dQbHVnaW4gZXh0ZW5kcyBQbHVnaW4ge1xuXG4gICAgYXN5bmMgb25sb2FkKCk6IFByb21pc2U8dm9pZD4ge1xuICAgICAgICBjb25zb2xlLmxvZyhcIlRvZG8gYnVpbGQgdGhlIGFwcGxpY2F0aW9uIVwiKVxuICAgIH1cblxuICAgIGFzeW5jIG9udW5sb2FkKCk6IFByb21pc2U8dm9pZD4ge1xuICAgICAgICBjb25zb2xlLmxvZyhcIlRvZG8gYnVpbGQgdGhlIGFwcGxpY2F0aW9uIVwiKVxuICAgIH1cblxufVxuIl0sCiAgIm1hcHBpbmdzIjogIjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUNBLHNCQUF1QjtBQUd2QixJQUFxQixZQUFyQixjQUF1Qyx1QkFBTztBQUFBLEVBRTFDLE1BQU0sU0FBd0I7QUFDMUIsWUFBUSxJQUFJLDZCQUE2QjtBQUFBLEVBQzdDO0FBQUEsRUFFQSxNQUFNLFdBQTBCO0FBQzVCLFlBQVEsSUFBSSw2QkFBNkI7QUFBQSxFQUM3QztBQUVKOyIsCiAgIm5hbWVzIjogW10KfQo=
